# Generated by Django 4.2.6 on 2023-10-30 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='body',
        ),
    ]
